---
title: "Project2"
author: "Calvin Moeller, Alexander Jahnsen"
date: "2024-12-06"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(shiny)

# Preprocess and sample data to avoid memory overload
spotify_1 <- read_csv('./dataset.csv')

spotify_raw <- spotify_1 %>%
  select(artists, popularity, danceability, energy, speechiness, acousticness, tempo, valence, liveness, track_name) %>%   # Select relevant variables
  filter(popularity > 60) %>% #We wanted to make sure the dataset wasn't too large, so we filtered by popularity
  arrange(desc(popularity)) 
  #sample_n(min(10000, n())) # Limit to 5000 rows to prevent memory overload

y = glimpse(spotify_raw)
artist_names = unique(spotify_raw$artists) #Create list of names outside of the dataset to help ease the workload of finding all the unique names.
```

```{r}


ui <- fluidPage(
  #Create a title and descriptive subtitle
  titlePanel(
    tags$div(
      HTML("<h1 style='margin-bottom: 5px;'>Spotify Data Visualization</h1>
           <p style='font-size: 18px; color: gray; margin-top: 0;'>Analyze song characteristics and popularity of your favorite artists.</p>")
    )),
  
  
  sidebarLayout(
    sidebarPanel(
      # Select/type any artists. Limit list to 40
      selectizeInput(
        inputId = "artist_filter", 
        label = "Select Artist(s). You can type the name and select from the list:",
        choices = artist_names,
        multiple = TRUE,
        options = list(maxOptions = 40),
        selected = c("The Neighbourhood", "OneRepublic", "Bad Bunny") #Force a few selections to ease loading 
      ),
      
       # Filter by popularity of songs
      "Affects all plots",
      sliderInput(
        "popularity_filter", 
        "Filter by Song Popularity:", 
        min = 60, max = 100, value = c(60, 100)
      ),
      
       # X/Y features to be graphed
      "Applies to both the bar and scatter plot:",
      selectInput(
        "x_feature", 
        "Music Characteristic 1:", 
        choices = c("danceability", "energy", "speechiness", "acousticness", "tempo", "valence", "liveness"), 
        selected = "acousticness"
      ),
      
      "Only applies to scatter plot:",
      selectInput(
        "y_feature", 
        "Music Characteristic 2:", 
        choices = c("danceability", "energy", "speechiness", "acousticness", "tempo", "valence", "liveness"), 
        selected = "energy"
      )
    ),
    
    mainPanel(
      tabsetPanel(    
        tabPanel("Popularity", plotOutput("popularity_plot"), tableOutput("population_table")),
        tabPanel("Bar Chart", plotOutput("feature_plot"), tableOutput("feature_table")),
        tabPanel("Scatterplot", plotOutput("scatter_plot"), tableOutput("var_table"))
      )
    )
  )
)

# Server
server <- function(input, output, session) {
  # Efficiently update dropdown for artists
  updateSelectizeInput(
    session,
    "artist_filter",
    choices = artist_names,
    server = TRUE,
    selected = c("The Neighbourhood", "OneRepublic", "Bad Bunny")
  )
  
  # Popularity Reactive filtering
  filtered_data <- reactive({
    data <- spotify_raw %>%
      filter(
        popularity >= input$popularity_filter[1],
        popularity <= input$popularity_filter[2]
      )
    # Check if not empty
    if (!is.null(input$artist_filter) && length(input$artist_filter) > 0) {
      data <- data %>% filter(artists %in% input$artist_filter)
    }
    return(data)
  })
  
  # Artist Popularity Plot
  output$popularity_plot <- renderPlot({
    filtered_data() %>%
      group_by(artists) %>%  # Group by artist
      summarise(average_popularity = mean(popularity, na.rm = TRUE)) %>%  # Calculate average popularity
      ggplot(aes(x = reorder(artists, -average_popularity), y = average_popularity, fill = artists)) +
      geom_bar(stat = "identity", show.legend = FALSE) +
      geom_text(aes(label = round(average_popularity,2)), vjust = 1.5, colour = "white") +
      labs(title = "Artist Average Popularity", x = "Artists", y = "Average Popularity") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    
  })
  
  # Artist Selected Feature Plot
  output$feature_plot <- renderPlot({
    filtered_data() %>%
      group_by(artists) %>%  # Group by artist
      summarise(average_feature = mean(get(input$x_feature), na.rm = TRUE)) %>%  # Calculate average selected feature
      ggplot(aes(x = reorder(artists, -average_feature), y = average_feature, fill = artists)) +
      geom_bar(stat = "identity", show.legend = FALSE) +
      geom_text(aes(label = round(average_feature,2)), vjust = 1.5, colour = "white") +
      labs(title = paste("Artist Average",input$x_feature), x = "Artists", y = paste("Average",input$x_feature)) +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    
  })

  
  # Scatter Plot for 2 features to compare
  output$scatter_plot <- renderPlot({
    
     # If no artists selected, plot all with no labels
    if(is.null(input$artist_filter)){
    plot <- filtered_data() %>%
      ggplot(aes_string(x = input$x_feature, y = input$y_feature)) +
      geom_point(color = "darkblue") +
      labs(title = paste("Song",input$x_feature,"in relation to",input$y_feature),
           x=input$x_feature,
           y=input$y_feature) +
      theme_minimal()
    }
     # Selected specific artists
    else{
    plot <- filtered_data() %>%
        ggplot(aes_string(x = input$x_feature, y = input$y_feature, color = "artists")) +  # Color by artist
        geom_point(size = 3) +
        labs(title = paste("Song",input$x_feature,"in relation to",input$y_feature),
        x=input$x_feature,
        y=input$y_feature) +
        theme_minimal()
    }
     # Label the track name under the point until cap at 4
    if(!is.null(input$artist_filter) && length(input$artist_filter) < 3){
      plot <- plot + geom_text(aes_string(label = "paste(track_name)", vjust = 1.7))
    
    }
    return(plot)
  })
  
  # Summary Table for Artist Popularity
  output$population_table <- renderTable({
    req(input$artist_filter)
      filtered_data() %>% 
        group_by(artists) %>%
        summarize(
          Min = min(popularity, na.rm = TRUE),
          Q1 = quantile(popularity, prob = .25, na.rm = TRUE),
          Median = median(popularity, na.rm = TRUE),
          Q3 = quantile(popularity, prob = .75, na.rm = TRUE),
          Max = max(popularity, na.rm = TRUE),
          Mean = mean(popularity, na.rm = TRUE),
          SD = sd(popularity, na.rm = TRUE),
          "Song Amount" = n()
      ) %>%
      as.data.frame()
  })
  
   # Summary Table for Artist Selected Feature
  output$feature_table <- renderTable({
    filtered_data() %>% 
      group_by(artists) %>%
      summarize(
        Min = min(get(input$x_feature), na.rm = TRUE),
        Q1 = quantile(get(input$x_feature), prob = .25, na.rm = TRUE),
        Median = median(get(input$x_feature), na.rm = TRUE),
        Q3 = quantile(get(input$x_feature), prob = .75, na.rm = TRUE),
        Max = max(get(input$x_feature), na.rm = TRUE),
        Mean = mean(get(input$x_feature), na.rm = TRUE),
        SD = sd(get(input$x_feature), na.rm = TRUE),
        "Song Amount" = n()
    ) %>%
    as.data.frame()
  })
  
  # Median table for scatterplot
  output$var_table <- renderTable({
    filtered_data() %>%
      summarize(
        "X-axis Median" = median(get(input$x_feature), na.rm = TRUE),
        "Y-axis Median" = median(get(input$y_feature), na.rm = TRUE),
        Observations = n()
      ) %>%
      as.data.frame()
  })
}

# Run the app
shinyApp(ui = ui, server = server)
```

